### ISSUE TITLE
Doesn't even work

### ISSUE THREAD

**Issue by Confusion010** [HackerHansen/Krunker-color-aimbot#7]

**Comment by HackerHansen** [comment]
This is pretty outdated, you have to turn the color variance up to like 30

**Comment by HackerHansen** [comment]
Nvm I thought this was another repo, I'll update it rn. If it still doesn't work it's a problem with your computer or graphics settings

**Comment by HackerHansen** [comment]
Ok it's updated, it should work now

**Comment by Confusion010** [comment]
Is it ok if i use violentmonkey

**Comment by Confusion010** [comment]
because when i copy and paste it into violent monkey it says invalid script

**Comment by Confusion010** [comment]
also what do i do with auto hotkey

**Comment by HackerHansen** [comment]
This isn't for violet monkey. You're supposed to download autohotkey and run the .ahk file directly.

**Comment by Confusion010** [comment]
Dang it my anti virus blocks me from opening the file
Is there a way to bypass this?
The antivirus I’m using is sophisticated home premium

**Comment by HackerHansen** [comment]
Your antivirus shouldn't be blocking anything, you're pretty much just pasting plain text lol 

I think you downloaded the wrong thing. Which file is it flagging?

**Comment by Confusion010** [comment]
The autohotkey

**Comment by Confusion010** [comment]
I got it working fine now but sometimes it randomly aims somewhere on the
ground or the wall

**Comment by HackerHansen** [comment]
Change your reticle color to something not red

**Comment by Confusion010** [comment]
Thanks for the tip!

**Comment by Confusion010** [comment]
Also sometimes it will lock onto a person but when I click with like a
sniper rifle it shoots just to the right like it locks on around their body
not on their body

**Comment by HackerHansen** [comment]
It does that if they're really far away, you can edit the offsets in the code if you want

**Comment by Confusion010** [comment]
scrnli_5_29_2021_6-12-31 PM.webm
<https://drive.google.com/file/d/1KYaQtSo-azvwwpug7zG0xxAsJTpf_Sqo/view?usp=drive_web>
